import React, { useState } from 'react';
import { 
  BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, 
  AreaChart, Area, PieChart, Pie, Cell
} from 'recharts';
import { TrendingUp, Package, Activity, Calendar, X } from 'lucide-react';
import '../dashboard/dashboard.css';

const monthlyData = [
  { name: 'Jan', revenue: 4000, costs: 2400, production: 2400 },
  { name: 'Feb', revenue: 3000, costs: 1398, production: 2210 },
  { name: 'Mar', revenue: 2000, costs: 9800, production: 2290 },
  { name: 'Apr', revenue: 2780, costs: 3908, production: 2000 },
  { name: 'May', revenue: 1890, costs: 4800, production: 2181 },
  { name: 'Jun', revenue: 2390, costs: 3800, production: 2500 },
  { name: 'Jul', revenue: 3490, costs: 4300, production: 2100 },
  { name: 'Aug', revenue: 4000, costs: 2400, production: 2400 },
  { name: 'Sep', revenue: 3000, costs: 1398, production: 2210 },
  { name: 'Oct', revenue: 2000, costs: 9800, production: 2290 },
  { name: 'Nov', revenue: 2780, costs: 3908, production: 2000 },
  { name: 'Dec', revenue: 3490, costs: 4300, production: 2100 },
];

const defectData = [
  { name: 'Color Variation', value: 400 },
  { name: 'Weaving Flaw', value: 300 },
  { name: 'Tear / Hole', value: 300 },
  { name: 'Staining', value: 200 },
];
const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042'];

const oeeData = [
  { name: 'Mon', oee: 88, availability: 92, performance: 95, quality: 99 },
  { name: 'Tue', oee: 85, availability: 89, performance: 94, quality: 98 },
  { name: 'Wed', oee: 91, availability: 95, performance: 97, quality: 98 },
  { name: 'Thu', oee: 89, availability: 93, performance: 96, quality: 99 },
  { name: 'Fri', oee: 92, availability: 96, performance: 98, quality: 99 },
  { name: 'Sat', oee: 86, availability: 90, performance: 92, quality: 97 },
  { name: 'Sun', oee: 87, availability: 91, performance: 93, quality: 97 },
];

export const Analytics: React.FC = () => {
  const [timeframe, setTimeframe] = useState('1 Year');
  const [showCustomModal, setShowCustomModal] = useState(false);
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');

  const handleTimeframeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const val = e.target.value;
    if (val === 'Custom Range...') {
      setShowCustomModal(true);
    } else {
      setTimeframe(val);
    }
  };

  const handleApplyCustomRange = () => {
    if (customStart && customEnd) {
      setTimeframe(`${customStart} to ${customEnd}`);
    }
    setShowCustomModal(false);
  };

  const handleGenerateReport = () => {
    const csvContent = `Report: Avenza Textiles Analytics\nTimeframe: ${timeframe}\n\nKPIs\nTotal Revenue,$3.4M\nProduction Volume,1.2M m\nOverall OEE,88.6%\n\nThis is an autogenerated custom analytics report for the selected duration.`;
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Analytics_Report_${timeframe.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="erp-dashboard">
      <div className="erp-page-header">
        <div>
          <h1 className="erp-page-title">Analytics</h1>
          <p className="erp-page-subtitle">Deep dive into AVENZA TEXTILES operational performance</p>
        </div>
        <div className="erp-header-actions" style={{ display: 'flex', gap: '1rem' }}>
          <select 
            className="erp-input" 
            style={{ width: '150px' }}
            value={timeframe}
            onChange={handleTimeframeChange}
          >
            <option>1 Week</option>
            <option>1 Month</option>
            <option>3 Months</option>
            <option>6 Months</option>
            <option>1 Year</option>
            <option>Custom Range...</option>
          </select>
          <button className="erp-btn erp-btn-primary" onClick={handleGenerateReport}>
            <Calendar size={16} style={{marginRight: '8px'}} /> Generate Custom Report
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.5rem', marginBottom: '1.5rem' }}>
        <div className="erp-panel">
          <div className="erp-panel-header">
            <h3 className="erp-panel-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <TrendingUp size={18} color="#0284c7" /> Total Revenue
            </h3>
          </div>
          <div className="erp-panel-body" style={{ textAlign: 'center', padding: '1rem' }}>
            <h2 style={{ fontSize: '2.5rem', fontWeight: 700, margin: '0', color: '#0f172a' }}>$3.4M</h2>
            <p style={{ color: '#10b981', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
               +12.5% <span style={{ color: '#64748b', fontWeight: 400 }}>vs last {timeframe.toLowerCase()}</span>
            </p>
          </div>
        </div>
        <div className="erp-panel">
          <div className="erp-panel-header">
            <h3 className="erp-panel-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Package size={18} color="#f59e0b" /> Production Volume
            </h3>
          </div>
          <div className="erp-panel-body" style={{ textAlign: 'center', padding: '1rem' }}>
            <h2 style={{ fontSize: '2.5rem', fontWeight: 700, margin: '0', color: '#0f172a' }}>1.2M m</h2>
            <p style={{ color: '#10b981', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
               +4.2% <span style={{ color: '#64748b', fontWeight: 400 }}>vs last {timeframe.toLowerCase()}</span>
            </p>
          </div>
        </div>
        <div className="erp-panel">
          <div className="erp-panel-header">
            <h3 className="erp-panel-title" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Activity size={18} color="#8b5cf6" /> Overall OEE
            </h3>
          </div>
          <div className="erp-panel-body" style={{ textAlign: 'center', padding: '1rem' }}>
            <h2 style={{ fontSize: '2.5rem', fontWeight: 700, margin: '0', color: '#0f172a' }}>88.6%</h2>
            <p style={{ color: '#ef4444', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px' }}>
               -1.1% <span style={{ color: '#64748b', fontWeight: 400 }}>vs last {timeframe.toLowerCase()}</span>
            </p>
          </div>
        </div>
      </div>

      {/* Charts Grid */}
      <div className="erp-panel-grid" style={{ gridTemplateColumns: '1fr 1fr' }}>
        
        {/* Revenue vs Costs Bar Chart */}
        <div className="erp-panel" style={{ height: '400px' }}>
          <div className="erp-panel-header">
            <h3 className="erp-panel-title">Revenue vs Costs ({timeframe})</h3>
          </div>
          <div className="erp-panel-body" style={{ height: 'calc(100% - 60px)' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthlyData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis axisLine={false} tickLine={false} />
                <Tooltip cursor={{fill: '#f1f5f9'}} />
                <Legend />
                <Bar dataKey="revenue" name="Revenue" fill="#0284c7" radius={[4, 4, 0, 0]} />
                <Bar dataKey="costs" name="Costs" fill="#ef4444" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Production Volume Line Chart */}
        <div className="erp-panel" style={{ height: '400px' }}>
          <div className="erp-panel-header">
            <h3 className="erp-panel-title">Production Volume Trends</h3>
          </div>
          <div className="erp-panel-body" style={{ height: 'calc(100% - 60px)' }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={monthlyData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis axisLine={false} tickLine={false} />
                <Tooltip />
                <Legend />
                <Line type="monotone" dataKey="production" name="Fabric Produced (m)" stroke="#10b981" strokeWidth={3} activeDot={{ r: 8 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* OEE Area Chart */}
        <div className="erp-panel" style={{ height: '400px' }}>
          <div className="erp-panel-header">
            <h3 className="erp-panel-title">Overall Equipment Effectiveness (OEE)</h3>
          </div>
          <div className="erp-panel-body" style={{ height: 'calc(100% - 60px)' }}>
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={oeeData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <defs>
                  <linearGradient id="colorOee" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis domain={[70, 100]} axisLine={false} tickLine={false} />
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <Tooltip />
                <Legend />
                <Area type="monotone" dataKey="oee" name="OEE (%)" stroke="#8b5cf6" fillOpacity={1} fill="url(#colorOee)" strokeWidth={3} />
                <Area type="monotone" dataKey="availability" name="Availability (%)" stroke="#94a3b8" fillOpacity={0} strokeWidth={2} strokeDasharray="5 5" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Defect Breakdown Pie Chart */}
        <div className="erp-panel" style={{ height: '400px' }}>
          <div className="erp-panel-header">
            <h3 className="erp-panel-title">Quality Defect Breakdown</h3>
          </div>
          <div className="erp-panel-body" style={{ height: 'calc(100% - 60px)', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={defectData}
                  cx="50%"
                  cy="50%"
                  innerRadius={80}
                  outerRadius={120}
                  fill="#8884d8"
                  paddingAngle={5}
                  dataKey="value"
                  label={({name, percent}) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}
                >
                  {defectData.map((_, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend verticalAlign="bottom" height={36}/>
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>
      
      {showCustomModal && (
        <div className="erp-modal-overlay">
          <div className="erp-modal" style={{ width: '400px' }}>
            <div className="erp-modal-header" style={{ borderBottom: '1px solid #e2e8f0', paddingBottom: '1rem', marginBottom: '1rem' }}>
              <h2 style={{ fontSize: '1.25rem', margin: 0 }}>Select Custom Duration</h2>
              <button className="erp-modal-close" onClick={() => setShowCustomModal(false)}>
                <X size={20} />
              </button>
            </div>
            <div className="erp-modal-body">
              <div style={{ marginBottom: '1rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', color: '#475569', fontSize: '0.9rem', fontWeight: 600 }}>Start Date</label>
                <input type="date" className="erp-input" style={{ width: '100%' }} value={customStart} onChange={e => setCustomStart(e.target.value)} />
              </div>
              <div style={{ marginBottom: '1.5rem' }}>
                <label style={{ display: 'block', marginBottom: '0.5rem', color: '#475569', fontSize: '0.9rem', fontWeight: 600 }}>End Date</label>
                <input type="date" className="erp-input" style={{ width: '100%' }} value={customEnd} onChange={e => setCustomEnd(e.target.value)} />
              </div>
              <button className="erp-btn erp-btn-primary" style={{ width: '100%', justifyContent: 'center' }} onClick={handleApplyCustomRange}>
                Apply Custom Range
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
